### ISSUE TITLE
#5 On the login page, there are two text boxes (User name and password) that you can type in and one login button that directs you to home page

### ISSUE THREAD

**Issue by XiangweiChen** [cse442-spring-2020-offering/cse442-semester-project-skr-2-0#22]
On the login page, there are two text boxes (User name and password) that you can type in and one login button that directs you to home page

**Comment by JerryLee0323** [comment]
Task Test:

1. The label "Username" alongside the textbox is properly displayed and the textbook accepts both letters and characters as input.
2. The label "Password" alongside the textbox is properly displayed and the textbook accepts both letters and characters as input.
