### ISSUE TITLE
As a student, I want to add a note to my schedule , so I can manage my time.

### ISSUE THREAD

**Issue by XiangweiChen** [cse442-spring-2020-offering/cse442-semester-project-skr-2-0#4]
Acceptance Test:

- [x]  Clicking a class on the calendar will bring up a popup with a textbox and a save button.

- [x]   After clicking the save button, if the textbox is empty, it does nothing. If the textbox is not empty, replace the existing note with the current note.

**Comment by JerryLee0323** [comment]
Acceptance Test:

1. Clicking a class on the calendar will bring up a popup with a textbook and a submit button.
2. After clicking the submit button, if the textbox is empty, it does nothing. If the textbox is not empty, replace the existing note with the current note. (You can check this by hovering over the class again after you submit)
3. After sharing the calendar to another student, if the other student checks your note, they will also see the note.
